
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from './componentes/Sidebar';
import BarNav from './componentes/BarNav';
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unibecarios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <Sidebar />

        {/* Contenido principal */}
        <div className="ml-64 w-full bg-white">
          <BarNav />
          <main className="p-8 pt-12">{children}</main>
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
